// Case o

const case0 = {
    "telp": "+6281224018624",
    "nama": "Muhammad Rayhan Fathurrakhman",
    "nama_confirm": "true",
    "rekening_confirm": "true",
    "telp_confirm": "true",
    "bakso": "true",
    "alamat": "Cangkuang Wetan, Dayeuhkolot, Kabupaten Bandung, Jawa Barat, Indonesia",
    "alamat_detail": "Isekai",
    "kewarganegaraan": "true",
    "nik": "767656455",
    "pekerjaan": "pns",
    "daftarkan_siapa": "0",
    "jenjang": "4",
    "nisn": "1283283",
    "kelamin": "1",
    "agama": "islam",
    "anak_ke": "2",
    "nama_ayah": "Ujang",
    "alamat_ayah": "Canggu, Jetis, Kabupaten Bantul, DI Yogyakarta, Indonesia",
    "alamat_ayah_detail": "London",
    "telp_ayah": "0811726327",
    "pekerjaan_ayah": "tni",
    "kewarganegaraan_ayah": "false",
    "kitas_ayah": "19328728",
    "nama_ibu": "Juliqana",
    "alamat_ibu": "Jumat, Talang Empat, Kabupaten Bengkulu Tengah, Bengkulu, Indonesia",
    "alamat_ibu_detail": "Morioh town",
    "telp_ibu": "0812371823",
    "pekerjaan_ibu": "dokter",
    "kewarganegaraan_ibu": "true",
    "nik_ibu": "77667565656",
    "has_wali": "true",
    "nama_wali": "Daddy Momon",
    "alamat_wali": "Ceurih Cot, Delima, Kabupaten Pidie, Nanggroe Aceh Darussalam, Indonesia",
    "alamat_wali_detail": "Clover Kingdom",
    "telp_wali": "0812323112",
    "pekerjaan_wali": "buruh",
    "kewarganegaraan_wali": "false",
    "kitas_wali": "3133123242"
}

// Case 1
const case1 = {
    "telp": "089633060648",
    "nama": "Muhammad Rayhan Fathurrakhman",
    "nama_confirm": "true",
    "rekening_confirm": "true",
    "telp_confirm": "true",
    "bakso": "true",
    "alamat": "Dieng Kulon, Batur, Kabupaten Banjarnegara, Jawa Tengah, Indonesia",
    "alamat_detail": "Banjarmasin",
    "kewarganegaraan": "true",
    "nik": "2932837923",
    "pekerjaan": "pemadam kebakaran",
    "daftarkan_siapa": "1",
    "nama_anak": "Muajirin",
    "kewarganegaraan_anak": "true",
    "nik_anak": "1313041492",
    "tinggal_bersama_confirm": "true",
    "alamat_anak": "Dieng Kulon, Batur, Kabupaten Banjarnegara, Jawa Tengah, Indonesia",
    "jenjang": "4",
    "nisn": "767857657",
    "kelamin": "0",
    "agama": "katholik",
    "anak_ke": "3",
    "select_ortu": "ayah",
    "menikah_confirm": "false",
    "masukan_pasangan": "true",
    "nama_ibu": "mdahan",
    "alamat_ibu": "Mudal, Boyolali, Kabupaten Boyolali, Jawa Tengah, Indonesia",
    "alamat_ibu_detail": "rerererere",
    "telp_ibu": "083038103",
    "pekerjaan_ibu": "staff kesehatan",
    "kewarganegaraan_ibu": "false",
    "kitas_ibu": "535354242",
    "has_wali": "true",
    "nama_wali": "wali",
    "alamat_wali": "Bunihayu, Jalancagak, Kabupaten Subang, Jawa Barat, Indonesia",
    "alamat_wali_detail": "Burnout",
    "telp_wali": "081931931",
    "pekerjaan_wali": "petani",
    "kewarganegaraan_wali": "true",
    "nik_wali": "453423131"
}

// Case 2
const case2 = {
    "telp": "089633060648",
    "nama": "mika",
    "nama_confirm": "true",
    "rekening_confirm": "true",
    "telp_confirm": "true",
    "bakso": "true",
    "alamat": "Muhajirin, Jambi Luar Kota, Kabupaten Muaro Jambi, Jambi, Indonesia",
    "alamat_detail": "Komplek Runjani 89, RT.6/RW.12, Blok J5 No.1",
    "kewarganegaraan": "true",
    "nik": "1392283728",
    "pekerjaan": "tni",
    "daftarkan_siapa": "2",
    "nama_anak": "Mujahidin",
    "kewarganegaraan_anak": "true",
    "nik_anak": "328372823",
    "tinggal_bersama_confirm": "true",
    "alamat_anak": "Muhajirin, Jambi Luar Kota, Kabupaten Muaro Jambi, Jambi, Indonesia",
    "jenjang": "2",
    "nisn": "",
    "kelamin": "0",
    "agama": "katholik",
    "anak_ke": "1",
    "nama_ayah": "yusha",
    "alamat_ayah": "Canggu, Jetis, Kabupaten Bantul, DI Yogyakarta, Indonesia",
    "alamat_ayah_detail": "Bangli 12, RT.4/RW.17",
    "telp_ayah": "183913139",
    "pekerjaan_ayah": "polisi",
    "kewarganegaraan_ayah": "true",
    "nik_ayah": "28",
    "nama_ibu": "Yunjin",
    "alamat_ibu": "Tanjung Salamat/Selamat, Portibi, Kabupaten Padang Lawas Utara, Sumatera Utara, Indonesia",
    "alamat_ibu_detail": "Krusial Sanggar 1, RT.2/RW.1, Rumah no 19",
    "telp_ibu": "081224018624",
    "pekerjaan_ibu": "tni",
    "kewarganegaraan_ibu": "false",
    "kitas_ibu": "829381"
}